-- return {}
-- require("mason").setup()
--
-- require("mason-lspconfig").setup({
--   ensure_installed = {
--     "pyright",        -- Python
--     "tsserver",       -- JavaScript/TypeScript
--     "bashls",         -- Bash
--     "clangd",         -- C/C++
--     "perlnavigator",  -- Perl
--     "lua_ls",         -- Lua
--     "html",
--     "cssls",
--   },
-- })

-- should contain the "nvim-lspconfig" server names for the language servers you want to install
-- https://github.com/neovim/nvim-lspconfig/blob/master/doc/configs.md
-- or by checking :help lspconfig-all
