[flavor]
#dark = "sunset"
#dark = "dracula"

#dark = "ayu-dark"
# https://github.com/kmlupreti/ayu-dark.yazi

# dark = "flexoki-dark"
# https://github.com/gosxrgxx/flexoki-dark.yazi

use = "monokai-vibrant"
# https://github.com/sanjinso/monokai-vibrant.yazi
