#!/usr/bin/env bash

# Vscode cleanup script controller

# Author : Bobby Valenzuela
# Created : 26th October 2022
# Last Modified : 26th October 2022

# Description:
# Used to run vscode-cleanup.sh on multiple remote machines in succession

# Usage: 
# ./vscode-cleanup-all

# Note: below assumes you've saved vscode-cleanup script in vscode-cleanup without ".sh" extension

echo "Running on hive01..."
ssh hive01 'bash -s' < /usr/local/bin/vscode-cleanup
echo ""

echo "Running on hive02..."
ssh hive02 'bash -s' < /usr/local/bin/vscode-cleanup
echo ""

echo "Running on hive03..."
ssh hive03 'bash -s' < /usr/local/bin/vscode-cleanup
echo ""

echo "Running on hive04..."
ssh hive04 'bash -s' < /usr/local/bin/vscode-cleanup
echo ""

echo "Running on hive05..."
ssh hive05 'bash -s' < /usr/local/bin/vscode-cleanup
echo ""

echo "Running on qbee..."
ssh queenbee 'bash -s' < /usr/local/bin/vscode-cleanup
echo ""

echo "Running on internal-api..."
ssh internal-api 'bash -s' < /usr/local/bin/vscode-cleanup
echo ""

echo "Running on papi..."
ssh papi 'bash -s' < /usr/local/bin/vscode-cleanup
echo ""


