#!/usr/bin/env bash

# Define custom colors using NEWT_COLORS
export NEWT_COLORS='
    root=green,black;
    border=green,black;
    title=green,black;
    shadow=black,gray;
    window=green,black;
    textbox=green,gray;
    entry=green,black;
    button=black,green;
    actbutton=white,green;
    listbox=green,black;
    actlistbox=yellow,black;
'


DURS_ROOT=/home/bobby/pbx/

# Confirm root dir has been Defined
[[ -z "$DURS_ROOT" ]] && echo "\$DURS_ROOT must be Defined. Exiting" && exit 0

OPTIONS_FULLPATHS=("placeholder")
OPTIONS=()
i=1
for dir in $(find $DURS_ROOT* -maxdepth 0 -type d -exec realpath '{}' \; | awk '{print tolower($0)}' | sort -k 1)
do
    dir_base=$(basename ${dir})
    OPTIONS+=("$i" "$dir_base")
    OPTIONS_FULLPATHS+=("$dir")
    ((i++))
done

# Add an exit option
OPTIONS+=("$i" "Exit")

# Create a menu using whiptail and store the selection
CHOICE=$(whiptail --nocancel --title "Dirs Menu" \
    --menu "Choose a directory:" \
    15 60 5 \
    "${OPTIONS[@]}" \
    3>&1 1>&2 2>&3)

# Selction is full path of collection
SELECTION=${OPTIONS_FULLPATHS[${CHOICE}]}
# echo "[+] i: $i"
# echo "[+] CHOICE: $CHOICE"
# echo "[+] SELECTION: $SELECTION"
# echo "[+] FULLARRAY: ${OPTIONS_FULLPATHS[@]}"

# Get array length
length=${#OPTIONS_FULLPATHS[@]}

# Check if num is not a valid index
if [ "$CHOICE" -gt 0 ] && [ "$CHOICE" -lt "$length" ]; then
    echo durrrrrrrrrr
    durs $SYSTEM $CHOICE
fi






